### ISSUE TITLE
memory corruption on malloc failure 

### ISSUE THREAD

**Issue by itaischwartz** [wasilibs/go-re2#102]
@anuraaga 
I believe I discovered an edge case in re2_cgo replace functions that can lead to freeing a non-allocated pointer.

https://github.com/wasilibs/go-re2/blob/38fdd8d191cbf6ed4c9a9fef6b8afaf1b97fa8d8/internal/re2_tinygowasm.go#L188-L195

In the above code, we are freeing `textAndTarget.ptr`, which is supposed to be allocated in the cpp code

https://github.com/wasilibs/go-re2/blob/38fdd8d191cbf6ed4c9a9fef6b8afaf1b97fa8d8/internal/cre2/cre2.cpp#L444-L460

In case of a `malloc` failure - we are freeing the original buffer, which leads to memory corruption.

It is straightforward to fix the memory corruption. However, there is an additional issue. The golang regexp API doesn't support returning errors, which means we'll have to break the API - either change the return type, or return a non-replaced string to the `ReplaceXX` methods.
Do you have a suggestion on how to fix this w/o breaking golang regex API?

**Comment by anuraaga** [comment]
Thanks a lot for the investigation! I didn't expect that malloc being a potential trouble point.

Just wondering, do you know why your app runs fine using the stdlib regex? Shouldn't a malloc failure here because of OOM and handling it somehow would still be an indication of the app not continuing to function? My initial idea is to panic if that malloc fails, but while it's a recoverable error unlike seg fault, it seems to not solve the fact that the app crashes in this situation.

**Comment by anuraaga** [comment]
Anyways I was able to avoid the issue of handling failed malloc entirely by reworking how replacement is done in #103, now we just use normal match methods instead of globalReplace. I don't expect this to reduce performance, if anything it may increase it by avoiding the intermediary malloc. If it does reduce it a little, though, it's probably still acceptable for gaining simpler code and the ability to implement `ReplaceFunc`.

Let me know if this fixes your issue.
