### ISSUE TITLE
Compile with -tags re_cgo under Windows

### ISSUE THREAD

**Issue by markusmobius** [wasilibs/go-re2#52]
Thanks for the library. I created a fork with very minor changes that allows compilation with cgo under Windows (MSYS2 - instructions are added to the README as well). Maybe it's possible to adjust your main library - then I can get rid of my fork.

The following  three files are changed:

https://github.com/markusmobius/go-re2/blob/main/internal/cre2/cre2.go

line 7: include stdint.h library
#include <stdint.h>

line 29: change of malloc signatures
void* malloc(size_t size);

line 110: change from ulong to uint64:
func Malloc(size int) unsafe.Pointer {
	return C.malloc(C.uint64_t(size))
}

https://github.com/markusmobius/go-re2/blob/main/internal/cre2/cre2_re2_cgo.go
Change of CXXFLAGS:
#cgo CXXFLAGS: -std=c++17

https://github.com/markusmobius/go-re2/blob/main/README.md
A short section on how to compile with re2_cgo under Ubuntu and Windows have been added (sorry for being verbose but I am not a cgo expert and it took me a while to figure out how to even install re2 on Ubuntu).

Everything still compiles under Ubuntu fine and the tests pass on both platforms.

**Comment by anuraaga** [comment]
Thanks! I'm guessing getting this to work with GitHub won't be trivial, but that's ok as the changes are small and work fine with the current build. If you're up for sending a PR, would be happy to get it in, or otherwise I can look at incorporating your changes. The only tweak I think would be in the readme adding a note that currently windows is not verified in CI.

**Comment by markusmobius** [comment]
I created a pull request and I added a note the README file about windows not verified in CI but you might want to edit that.

Thanks!
