### ISSUE TITLE
v1.5.0-pre.1 has slowed down

### ISSUE THREAD

**Issue by wujincheng2333** [wasilibs/go-re2#72]
Compare with v1.4.1.

**Comment by anuraaga** [comment]
Hi @wujincheng2333 - can you provide any numbers? Also are you able to provide any RAM usage information? The expectation with 1.5.0 is

- Much less RAM usage
- Better concurrent performance
- A little slower on non-concurrent

In the benchmarks here we haven't seen a huge slowdown in non-concurrent but it will help to have more real-world information if you can provide it.

**Comment by wujincheng2333** [comment]
Thanks for the response.
Single-threaded request testing.
<img width="1581" alt="image" src="https://github.com/wasilibs/go-re2/assets/39256897/be46d354-ca4e-4f56-bb12-12367983ff86">
<img width="1583" alt="image" src="https://github.com/wasilibs/go-re2/assets/39256897/82b5c83b-15ca-45ec-8001-f3869009e705">
<img width="1598" alt="image" src="https://github.com/wasilibs/go-re2/assets/39256897/007fdab3-343f-480c-b9d9-fdbdd38e3b61">

**Comment by anuraaga** [comment]
Thanks for the numbers! I guess RAM usage might not be in them perhaps it's not easy for you to get that. But I think the slowdown is around ~20%. While I'll see if there is any low hanging fruit to recover some of it, I believe we will accept that for the next release to get the other improvements now that we support usage of re2 with threads. We have unavoidable new overhead in proper memory management of inputs, before we could reuse buffers across all calls since there was no concurrent access. Hopefully the performance improvement vs standard library is still enough to be useful.

For context, in #69 we see gigabytes less RAM usage with Wasm version with the new approach.

**Comment by wujincheng2333** [comment]
Thank you for your answer. We place more emphasis on performance. We use cgo for static compilation.
